# Use the official PostgreSQL as the base image
FROM postgres

# Copy the initialization script to the container
COPY data.sql /docker-entrypoint-initdb.d/

# Set environment variables for PostgreSQL configuration
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD mysecretpassword
ENV POSTGRES_DB git_docked_db